spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

adapter:
  micro-plazoleta:
    url: ${PLAZOLETA_SERVICE_URL}

feign:
  client:
    config:
      micro-plazoleta:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
